# Wade Poltenovage Programming assignment 1 part 1:
#Write a program using a 2D array (i.e., 2D matrices) that generates and writes out four
#matrices defined below. The values in these four initial matrices must be generated by the
#program and not hard-coded.

# Dimensions
first_name = "Wade"
last_name = "Poltenovage"
rows = len(last_name)
cols = len(first_name)

# Display the lengths of the first and last names
print("First Name: " + str(first_name) + " Length: " + str(cols))
print("Last Name: " + str(last_name) +" Length: " + str(rows))

# Function to write matrix to a file
def write_matrix_to_file(matrix, filename):
    with open(filename, "w") as f:
        for row in matrix:
            f.write(" ".join(map(str, row)) + "\n")

# Mat1: Fill by columns first, then rows
mat1 = [[0 for _ in range(cols)] for _ in range(rows)]
value = 1
for col in range(cols):
    for row in range(rows):
        mat1[row][col] = value
        value += 1

# Write Mat1 to file
write_matrix_to_file(mat1, "wpoltenovage_mat1.txt")

# Mat2: Fill by rows first, then columns
mat2 = [[0 for _ in range(cols)] for _ in range(rows)]
value = 2
for row in range(rows):
    for col in range(cols):
        mat2[row][col] = value
        value += 3

# Write Mat2 to file
write_matrix_to_file(mat2, "wpoltenovage_mat2.txt")

# Mat3: 2 Rows, 4 Columns; Fill by columns first, then rows, starting from 10 decreasing by 2
mat3 = [[0 for _ in range(4)] for _ in range(2)]
value = 10
for col in range(4):
    for row in range(2):
        mat3[row][col] = value
        value -= 2

# Write Mat3 to file
write_matrix_to_file(mat3, "wpoltenovage_mat3.txt")

# Mat4: 4 Rows, 2 Columns; Fill by rows first, then columns, starting from -6 increasing by 1.5
mat4 = [[0 for _ in range(2)] for _ in range(4)]
value = -6
for row in range(4):
    for col in range(2):
        mat4[row][col] = value
        value += 1.5

# Write Mat4 to file
write_matrix_to_file(mat4, "wpoltenovage_mat4.txt")

print("Matrices written to files.")
